version: "3.9"

services:
  # AUTH SERVICE
  auth-db:
    image: postgres:15
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - spacemaster-net

  auth-service:
    build: ./auth-service
    environment:
      DATABASE_URL: postgresql://postgres:postgres@auth-db:5432/auth_db
    depends_on:
      auth-db:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - spacemaster-net

  # VENUE SERVICE
  venue-db:
    image: postgres:15
    environment:
      POSTGRES_DB: venue_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - spacemaster-net

  venue-service:
    build: ./venue-service
    environment:
      DATABASE_URL: postgresql://postgres:postgres@venue-db:5432/venue_db
    depends_on:
      venue-db:
        condition: service_healthy
    ports:
      - "8001:8000"
    networks:
      - spacemaster-net

  # ROOM SERVICE
  room-db:
    image: postgres:15
    environment:
      POSTGRES_DB: room_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - spacemaster-net

  room-service:
    build: ./room-service
    environment:
      DATABASE_URL: postgresql://postgres:postgres@room-db:5432/room_db
    depends_on:
      room-db:
        condition: service_healthy
    ports:
      - "8002:8000"
    networks:
      - spacemaster-net

  # SCHEDULE SERVICE

  schedule-db:
    image: postgres:15
    environment:
      POSTGRES_DB: schedule_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - spacemaster-net

  schedule-service:
    build: ./schedule-service
    environment:
      DATABASE_URL: postgresql://postgres:postgres@schedule-db:5432/schedule_db
    depends_on:
      schedule-db:
        condition: service_healthy
    ports:
      - "8003:8000"
    networks:
      - spacemaster-net

  # SPACEMASTER GATEWAY
  spacemaster-gateway:
    build: ./spacemaster-gateway
    environment:
      VENUE_SERVICE_URL: http://venue-service:8000/graphql
      ROOM_SERVICE_URL: http://room-service:8000/graphql
      SCHEDULE_SERVICE_URL: http://schedule-service:8000/graphql
    ports:
      - "8004:8000"
    networks:
      - spacemaster-net


# NETWORK
networks:
  spacemaster-net:
    driver: bridge

volumes:
  venue_data:
  room_data:
  schedule_data:
